/* ============================================
   מאגר מסלולים בישראל
   ============================================ */

const TRAILS = [
    {
        id: 'ein-hemed',
        name: 'גן לאומי עין חמד',
        region: 'jerusalem',
        regionName: 'הרי ירושלים',
        type: 'water',
        distance_km: 1.5,
        ascent_m: 30,
        duration_min: 90,
        difficulty: 1,
        start: { lat: 31.7986, lon: 35.1267, name: 'כניסה ראשית עין חמד' },
        end:   { lat: 31.7986, lon: 35.1267, name: 'כניסה ראשית עין חמד' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: true, petFriendly: false, shade: 'high', water: true, circular: true, exposure: 'low' },
        description: 'גן לאומי קסום עם מעיין, ברכה רדודה, מדשאות ענק וצל של עצים עתיקים. מסלול מעגלי מישורי וקצר — מושלם למשפחות, לעגלות ולמי שמעדיף נחת.',
        season: ['winter','spring','summer','autumn']
    },
    {
        id: 'ben-shemen',
        name: 'יער בן שמן — שביל המעיינות',
        region: 'center',
        regionName: 'מרכז הארץ',
        type: 'forest',
        distance_km: 3.2,
        ascent_m: 60,
        duration_min: 90,
        difficulty: 1,
        start: { lat: 31.9560, lon: 34.9750, name: 'חניון יער בן שמן' },
        end:   { lat: 31.9560, lon: 34.9750, name: 'חניון יער בן שמן' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: true, petFriendly: true, shade: 'high', water: false, circular: true, exposure: 'low' },
        description: 'יער קק"ל פתוח עם שבילים רחבים, פינות פיקניק, מתקני משחק ומסלול נגיש לעגלות. נעים גם בקיץ בזכות הצל הצפוף.',
        season: ['winter','spring','summer','autumn']
    },
    {
        id: 'armon-hanatziv',
        name: 'טיילת ארמון הנציב',
        region: 'jerusalem',
        regionName: 'ירושלים',
        type: 'archaeology',
        distance_km: 2.0,
        ascent_m: 20,
        duration_min: 60,
        difficulty: 1,
        start: { lat: 31.7530, lon: 35.2280, name: 'תחילת הטיילת' },
        end:   { lat: 31.7530, lon: 35.2280, name: 'תחילת הטיילת' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: true, petFriendly: true, shade: 'medium', water: false, circular: false, exposure: 'medium' },
        description: 'טיילת מרוצפת עם תצפית פנורמית על העיר העתיקה, הר הבית והר הזיתים. שלווה, נגישה וקצרה — נהדרת לשקיעה.',
        season: ['winter','spring','summer','autumn']
    },
    {
        id: 'caesarea-coast',
        name: 'חוף הסלעים בקיסריה',
        region: 'center',
        regionName: 'חוף השרון',
        type: 'coast',
        distance_km: 3.5,
        ascent_m: 15,
        duration_min: 90,
        difficulty: 1,
        start: { lat: 32.5100, lon: 34.8930, name: 'חניון נמל קיסריה' },
        end:   { lat: 32.5100, lon: 34.8930, name: 'חניון נמל קיסריה' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: false, petFriendly: true, shade: 'low', water: true, circular: true, exposure: 'high' },
        description: 'הליכה לאורך החוף בקיסריה עם עתיקות רומיות, אקוודוקט מרשים ומפלצי גלים. גם המקום לעצור לקפה.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'nahal-amud',
        name: 'נחל עמוד התחתון',
        region: 'galilee',
        regionName: 'גליל עליון',
        type: 'water',
        distance_km: 6.5,
        ascent_m: 280,
        duration_min: 240,
        difficulty: 3,
        start: { lat: 32.8800, lon: 35.4900, name: 'חניון הכבל / מבואות' },
        end:   { lat: 32.8520, lon: 35.5100, name: 'יציאה לטבריה' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: false, strollerFriendly: false, petFriendly: true, shade: 'medium', water: true, circular: false, exposure: 'medium' },
        description: 'מסלול קלאסי לאורך הנחל הזורם, מעבר בין צוקים, ברכות חורף וחורבות. דרוש כיוון יציאה נפרד או רכב שני.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'arbel',
        name: 'הר ארבל — שביל המצוק',
        region: 'galilee',
        regionName: 'גליל תחתון',
        type: 'desert',
        distance_km: 4.5,
        ascent_m: 380,
        duration_min: 210,
        difficulty: 4,
        start: { lat: 32.8264, lon: 35.5050, name: 'חניון הר ארבל' },
        end:   { lat: 32.8264, lon: 35.5050, name: 'חניון הר ארבל' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: false, strollerFriendly: false, petFriendly: false, shade: 'low', water: false, circular: true, exposure: 'high' },
        description: 'תצפית בלתי נשכחת על הכנרת, ירידה דרך מצוק עם שלבי ברזל ומאחזי יד. מאתגר אך לא ארוך. דורש כושר וביטחון בגובה.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'ein-gedi-david',
        name: 'נחל דוד — עין גדי',
        region: 'deadSea',
        regionName: 'ים המלח',
        type: 'water',
        distance_km: 2.5,
        ascent_m: 150,
        duration_min: 120,
        difficulty: 2,
        start: { lat: 31.4660, lon: 35.3900, name: 'כניסה לשמורת עין גדי' },
        end:   { lat: 31.4660, lon: 35.3900, name: 'כניסה לשמורת עין גדי' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: true, strollerFriendly: false, petFriendly: false, shade: 'medium', water: true, circular: true, exposure: 'medium' },
        description: 'נווה מדבר עם בריכות, מפל דוד ויעלים. מסלול קצר ורטוב, נעים גם בקיץ בזכות המים.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'masada-snake',
        name: 'מצדה — שביל הנחש',
        region: 'deadSea',
        regionName: 'ים המלח',
        type: 'archaeology',
        distance_km: 2.5,
        ascent_m: 350,
        duration_min: 90,
        difficulty: 4,
        start: { lat: 31.3150, lon: 35.3580, name: 'מצדה צד מזרח' },
        end:   { lat: 31.3160, lon: 35.3530, name: 'פסגת מצדה' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: false, strollerFriendly: false, petFriendly: false, shade: 'low', water: false, circular: false, exposure: 'high' },
        description: 'עלייה תלולה לפסגת מצדה לזריחה. בקיץ — רק עד 8:30 בבוקר. אפשר לרדת ברכבל. מומלץ ליוצאים מוקדם.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'ramon-ari',
        name: 'מכתש רמון — לוע הארי',
        region: 'negev',
        regionName: 'נגב',
        type: 'desert',
        distance_km: 5.0,
        ascent_m: 180,
        duration_min: 180,
        difficulty: 3,
        start: { lat: 30.5600, lon: 34.8400, name: 'חניון פארסה' },
        end:   { lat: 30.5600, lon: 34.8400, name: 'חניון פארסה' },
        flags: { backFriendly: false, kneeFriendly: true, kidsFriendly: false, strollerFriendly: false, petFriendly: true, shade: 'low', water: false, circular: true, exposure: 'high' },
        description: 'נופים אדמדמים, סלעים פראיים ומבנה גיאולוגי מרהיב בלב המכתש. מסלול לרגלי הר אריף — לא קשה אבל חשוף.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'nahal-prat',
        name: 'נחל פרת — עין מבוע',
        region: 'jerusalem',
        regionName: 'מדבר יהודה',
        type: 'water',
        distance_km: 3.0,
        ascent_m: 80,
        duration_min: 120,
        difficulty: 2,
        start: { lat: 31.8350, lon: 35.3270, name: 'חניון עין מבוע' },
        end:   { lat: 31.8350, lon: 35.3270, name: 'חניון עין מבוע' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: false, petFriendly: true, shade: 'medium', water: true, circular: true, exposure: 'medium' },
        description: 'אחד הנחלים הקסומים ליד ירושלים — מים זורמים, צמחיית גדות ובריכות לרחצה. נעים גם בקיץ.',
        season: ['winter','spring','summer','autumn']
    },
    {
        id: 'meshushim',
        name: 'ברכת המשושים',
        region: 'golan',
        regionName: 'גולן',
        type: 'water',
        distance_km: 3.0,
        ascent_m: 90,
        duration_min: 120,
        difficulty: 2,
        start: { lat: 32.9170, lon: 35.6890, name: 'חניון ברכת המשושים' },
        end:   { lat: 32.9170, lon: 35.6890, name: 'חניון ברכת המשושים' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: true, strollerFriendly: false, petFriendly: false, shade: 'medium', water: true, circular: true, exposure: 'medium' },
        description: 'ברכה טבעית מוקפת עמודי בזלת משושים. שחייה במים קרירים, ירידה במדרגות. תופעת טבע ייחודית.',
        season: ['spring','summer','autumn']
    },
    {
        id: 'yehudia',
        name: 'נחל יהודיה',
        region: 'golan',
        regionName: 'גולן',
        type: 'water',
        distance_km: 7.0,
        ascent_m: 200,
        duration_min: 300,
        difficulty: 4,
        start: { lat: 32.9410, lon: 35.7090, name: 'חניון יהודיה' },
        end:   { lat: 32.9410, lon: 35.7090, name: 'חניון יהודיה' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: false, strollerFriendly: false, petFriendly: false, shade: 'medium', water: true, circular: true, exposure: 'medium' },
        description: 'מסלול מים מאתגר עם קפיצה לבריכה, סולמות והליכה בנחל. דורש שחייה. אחד הקלאסיים של הגולן.',
        season: ['spring','summer','autumn']
    },
    {
        id: 'yatir',
        name: 'יער יתיר — שביל המנזר',
        region: 'negev',
        regionName: 'דרום הר חברון',
        type: 'forest',
        distance_km: 4.0,
        ascent_m: 100,
        duration_min: 120,
        difficulty: 2,
        start: { lat: 31.3650, lon: 35.0660, name: 'חניון יער יתיר' },
        end:   { lat: 31.3650, lon: 35.0660, name: 'חניון יער יתיר' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: false, petFriendly: true, shade: 'high', water: false, circular: true, exposure: 'low' },
        description: 'היער הגדול בישראל — אורנים, נופים פתוחים על המדבר ועתיקות ביזנטיות. שקט אמיתי.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'kursi',
        name: 'גן לאומי כורסי',
        region: 'galilee',
        regionName: 'מזרח הכנרת',
        type: 'archaeology',
        distance_km: 1.2,
        ascent_m: 25,
        duration_min: 75,
        difficulty: 1,
        start: { lat: 32.8260, lon: 35.6510, name: 'גן לאומי כורסי' },
        end:   { lat: 32.8260, lon: 35.6510, name: 'גן לאומי כורסי' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: true, petFriendly: true, shade: 'medium', water: false, circular: true, exposure: 'medium' },
        description: 'מנזר ביזנטי משוחזר עם פסיפסים ססגוניים, נגיש לעגלות וכיסאות גלגלים.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'tabor',
        name: 'הר תבור',
        region: 'galilee',
        regionName: 'גליל תחתון',
        type: 'archaeology',
        distance_km: 5.0,
        ascent_m: 350,
        duration_min: 180,
        difficulty: 3,
        start: { lat: 32.6870, lon: 35.3920, name: 'חניון הר תבור' },
        end:   { lat: 32.6870, lon: 35.3920, name: 'חניון הר תבור' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: false, strollerFriendly: false, petFriendly: true, shade: 'medium', water: false, circular: true, exposure: 'medium' },
        description: 'הר ברור עם תצפית מרשימה על העמק. אפשר גם לעלות עם רכב — אבל המסלול מתגמל.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'megiddo',
        name: 'יער מגידו',
        region: 'carmel',
        regionName: 'עמק יזרעאל',
        type: 'forest',
        distance_km: 2.5,
        ascent_m: 50,
        duration_min: 75,
        difficulty: 1,
        start: { lat: 32.5840, lon: 35.1830, name: 'חניון יער מגידו' },
        end:   { lat: 32.5840, lon: 35.1830, name: 'חניון יער מגידו' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: true, petFriendly: true, shade: 'high', water: false, circular: true, exposure: 'low' },
        description: 'יער קק"ל מטופח עם מסלולים סלולים, מתקנים למשפחות וגישה לעגלות.',
        season: ['winter','spring','summer','autumn']
    },
    {
        id: 'ein-afek',
        name: 'שמורת עין אפק',
        region: 'galilee',
        regionName: 'מפרץ חיפה',
        type: 'water',
        distance_km: 2.0,
        ascent_m: 10,
        duration_min: 90,
        difficulty: 1,
        start: { lat: 32.8500, lon: 35.1140, name: 'שמורת עין אפק' },
        end:   { lat: 32.8500, lon: 35.1140, name: 'שמורת עין אפק' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: true, petFriendly: false, shade: 'high', water: true, circular: true, exposure: 'low' },
        description: 'שמורה רטובה עם מסלול מעגלי על גבי גשרון עץ, ציפורי ביצה, ותחנת חוקרים. נגיש לעגלות.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'achziv',
        name: 'נחל אכזיב — הגשרים',
        region: 'galilee',
        regionName: 'גליל מערבי',
        type: 'water',
        distance_km: 4.5,
        ascent_m: 120,
        duration_min: 180,
        difficulty: 3,
        start: { lat: 33.0510, lon: 35.2210, name: 'חניון יחיעם' },
        end:   { lat: 33.0510, lon: 35.2210, name: 'חניון יחיעם' },
        flags: { backFriendly: false, kneeFriendly: false, kidsFriendly: false, strollerFriendly: false, petFriendly: true, shade: 'medium', water: true, circular: true, exposure: 'medium' },
        description: 'נחל בזרימה איתנה בחורף ובאביב, גשרים תלויים, יערות אלון וטחנות קמח עתיקות.',
        season: ['winter','spring']
    },
    {
        id: 'nahal-kalt',
        name: 'נחל קלת — אילת',
        region: 'eilat',
        regionName: 'הרי אילת',
        type: 'desert',
        distance_km: 3.5,
        ascent_m: 160,
        duration_min: 150,
        difficulty: 3,
        start: { lat: 29.6090, lon: 34.9200, name: 'חניון נחל קלת' },
        end:   { lat: 29.6090, lon: 34.9200, name: 'חניון נחל קלת' },
        flags: { backFriendly: false, kneeFriendly: true, kidsFriendly: true, strollerFriendly: false, petFriendly: true, shade: 'low', water: false, circular: true, exposure: 'high' },
        description: 'נוף מדברי דרמטי, סלעי גרניט אדומים ועצי שיטה. בקיץ — רק שעות הבוקר המוקדמות.',
        season: ['winter','spring','autumn']
    },
    {
        id: 'carmel-little-switzerland',
        name: 'שווייץ הקטנה — הכרמל',
        region: 'carmel',
        regionName: 'הכרמל',
        type: 'forest',
        distance_km: 3.0,
        ascent_m: 120,
        duration_min: 120,
        difficulty: 2,
        start: { lat: 32.7240, lon: 35.0190, name: 'חניון בית אורן' },
        end:   { lat: 32.7240, lon: 35.0190, name: 'חניון בית אורן' },
        flags: { backFriendly: true, kneeFriendly: true, kidsFriendly: true, strollerFriendly: false, petFriendly: true, shade: 'high', water: false, circular: true, exposure: 'low' },
        description: 'יער ים תיכוני סבוך, אלונים גדולים, שבילים מקסימים בין מצוקים — קריר וצלול גם בקיץ.',
        season: ['winter','spring','summer','autumn']
    }
];

window.TRAILS = TRAILS;
