/* ============================================
   English Quest 3D - Word Database
   ============================================ */

const WORD_DATABASE = {
    beginner: [
        { en: "cat", he: "חתול", phonetic: "/kæt/", example: "The ___ is sleeping.", exampleHe: "החתול ישן." },
        { en: "dog", he: "כלב", phonetic: "/dɒɡ/", example: "I love my ___.", exampleHe: "אני אוהב את הכלב שלי." },
        { en: "house", he: "בית", phonetic: "/haʊs/", example: "This is my ___.", exampleHe: "זה הבית שלי." },
        { en: "water", he: "מים", phonetic: "/ˈwɔːtər/", example: "I drink ___.", exampleHe: "אני שותה מים." },
        { en: "food", he: "אוכל", phonetic: "/fuːd/", example: "The ___ is delicious.", exampleHe: "האוכל טעים." },
        { en: "book", he: "ספר", phonetic: "/bʊk/", example: "I read a ___.", exampleHe: "אני קורא ספר." },
        { en: "tree", he: "עץ", phonetic: "/triː/", example: "The ___ is tall.", exampleHe: "העץ גבוה." },
        { en: "sun", he: "שמש", phonetic: "/sʌn/", example: "The ___ is bright.", exampleHe: "השמש בוהקת." },
        { en: "moon", he: "ירח", phonetic: "/muːn/", example: "The ___ is full tonight.", exampleHe: "הירח מלא הלילה." },
        { en: "star", he: "כוכב", phonetic: "/stɑːr/", example: "I see a ___ in the sky.", exampleHe: "אני רואה כוכב בשמיים." },
        { en: "fish", he: "דג", phonetic: "/fɪʃ/", example: "The ___ swims fast.", exampleHe: "הדג שוחה מהר." },
        { en: "bird", he: "ציפור", phonetic: "/bɜːrd/", example: "The ___ can fly.", exampleHe: "הציפור יכולה לעוף." },
        { en: "red", he: "אדום", phonetic: "/rɛd/", example: "The apple is ___.", exampleHe: "התפוח אדום." },
        { en: "blue", he: "כחול", phonetic: "/bluː/", example: "The sky is ___.", exampleHe: "השמיים כחולים." },
        { en: "green", he: "ירוק", phonetic: "/ɡriːn/", example: "The grass is ___.", exampleHe: "הדשא ירוק." },
        { en: "big", he: "גדול", phonetic: "/bɪɡ/", example: "The elephant is ___.", exampleHe: "הפיל גדול." },
        { en: "small", he: "קטן", phonetic: "/smɔːl/", example: "The mouse is ___.", exampleHe: "העכבר קטן." },
        { en: "happy", he: "שמח", phonetic: "/ˈhæpi/", example: "I am very ___.", exampleHe: "אני מאוד שמח." },
        { en: "sad", he: "עצוב", phonetic: "/sæd/", example: "She looks ___.", exampleHe: "היא נראית עצובה." },
        { en: "friend", he: "חבר", phonetic: "/frɛnd/", example: "You are my best ___.", exampleHe: "אתה החבר הכי טוב שלי." },
        { en: "love", he: "אהבה", phonetic: "/lʌv/", example: "I ___ you.", exampleHe: "אני אוהב אותך." },
        { en: "hand", he: "יד", phonetic: "/hænd/", example: "Give me your ___.", exampleHe: "תן לי את היד שלך." },
        { en: "eye", he: "עין", phonetic: "/aɪ/", example: "I see with my ___.", exampleHe: "אני רואה עם העין שלי." },
        { en: "milk", he: "חלב", phonetic: "/mɪlk/", example: "I drink ___ every morning.", exampleHe: "אני שותה חלב כל בוקר." },
        { en: "bread", he: "לחם", phonetic: "/brɛd/", example: "I eat ___ for breakfast.", exampleHe: "אני אוכל לחם לארוחת בוקר." },
        { en: "door", he: "דלת", phonetic: "/dɔːr/", example: "Please close the ___.", exampleHe: "בבקשה סגור את הדלת." },
        { en: "chair", he: "כיסא", phonetic: "/tʃɛr/", example: "Sit on the ___.", exampleHe: "שב על הכיסא." },
        { en: "table", he: "שולחן", phonetic: "/ˈteɪbəl/", example: "The book is on the ___.", exampleHe: "הספר על השולחן." },
        { en: "boy", he: "ילד", phonetic: "/bɔɪ/", example: "The ___ is playing.", exampleHe: "הילד משחק." },
        { en: "girl", he: "ילדה", phonetic: "/ɡɜːrl/", example: "The ___ is reading.", exampleHe: "הילדה קוראת." },
    ],
    intermediate: [
        { en: "beautiful", he: "יפה", phonetic: "/ˈbjuːtɪfəl/", example: "The sunset is ___.", exampleHe: "השקיעה יפה." },
        { en: "important", he: "חשוב", phonetic: "/ɪmˈpɔːrtənt/", example: "This is very ___.", exampleHe: "זה מאוד חשוב." },
        { en: "different", he: "שונה", phonetic: "/ˈdɪfərənt/", example: "Every person is ___.", exampleHe: "כל אדם שונה." },
        { en: "possible", he: "אפשרי", phonetic: "/ˈpɒsɪbəl/", example: "Everything is ___.", exampleHe: "הכל אפשרי." },
        { en: "together", he: "ביחד", phonetic: "/təˈɡɛðər/", example: "Let's work ___.", exampleHe: "בואו נעבוד ביחד." },
        { en: "between", he: "בין", phonetic: "/bɪˈtwiːn/", example: "Stand ___ the two trees.", exampleHe: "עמוד בין שני העצים." },
        { en: "problem", he: "בעיה", phonetic: "/ˈprɒbləm/", example: "We have a ___.", exampleHe: "יש לנו בעיה." },
        { en: "answer", he: "תשובה", phonetic: "/ˈɑːnsər/", example: "I know the ___.", exampleHe: "אני יודע את התשובה." },
        { en: "question", he: "שאלה", phonetic: "/ˈkwɛstʃən/", example: "May I ask a ___?", exampleHe: "אפשר לשאול שאלה?" },
        { en: "country", he: "מדינה", phonetic: "/ˈkʌntri/", example: "Israel is a small ___.", exampleHe: "ישראל היא מדינה קטנה." },
        { en: "language", he: "שפה", phonetic: "/ˈlæŋɡwɪdʒ/", example: "English is a global ___.", exampleHe: "אנגלית היא שפה גלובלית." },
        { en: "remember", he: "לזכור", phonetic: "/rɪˈmɛmbər/", example: "I ___ your name.", exampleHe: "אני זוכר את השם שלך." },
        { en: "understand", he: "להבין", phonetic: "/ˌʌndərˈstænd/", example: "I ___ the lesson.", exampleHe: "אני מבין את השיעור." },
        { en: "believe", he: "להאמין", phonetic: "/bɪˈliːv/", example: "I ___ in you.", exampleHe: "אני מאמין בך." },
        { en: "explain", he: "להסביר", phonetic: "/ɪkˈspleɪn/", example: "Please ___ this to me.", exampleHe: "בבקשה תסביר לי את זה." },
        { en: "weather", he: "מזג אוויר", phonetic: "/ˈwɛðər/", example: "The ___ is nice today.", exampleHe: "מזג האוויר נחמד היום." },
        { en: "travel", he: "לטייל", phonetic: "/ˈtrævəl/", example: "I love to ___.", exampleHe: "אני אוהב לטייל." },
        { en: "decision", he: "החלטה", phonetic: "/dɪˈsɪʒən/", example: "Make a ___.", exampleHe: "קבל החלטה." },
        { en: "experience", he: "ניסיון", phonetic: "/ɪkˈspɪriəns/", example: "It was a great ___.", exampleHe: "זה היה ניסיון מעולה." },
        { en: "knowledge", he: "ידע", phonetic: "/ˈnɒlɪdʒ/", example: "___ is power.", exampleHe: "ידע זה כוח." },
        { en: "discover", he: "לגלות", phonetic: "/dɪˈskʌvər/", example: "Let's ___ something new.", exampleHe: "בואו נגלה משהו חדש." },
        { en: "hospital", he: "בית חולים", phonetic: "/ˈhɒspɪtəl/", example: "She works at the ___.", exampleHe: "היא עובדת בבית החולים." },
        { en: "suddenly", he: "פתאום", phonetic: "/ˈsʌdənli/", example: "___ the light went off.", exampleHe: "פתאום האור כבה." },
        { en: "company", he: "חברה", phonetic: "/ˈkʌmpəni/", example: "He started a ___.", exampleHe: "הוא הקים חברה." },
        { en: "education", he: "חינוך", phonetic: "/ˌɛdjʊˈkeɪʃən/", example: "___ is the key to success.", exampleHe: "חינוך הוא המפתח להצלחה." },
        { en: "continue", he: "להמשיך", phonetic: "/kənˈtɪnjuː/", example: "Please ___ reading.", exampleHe: "בבקשה המשך לקרוא." },
        { en: "famous", he: "מפורסם", phonetic: "/ˈfeɪməs/", example: "She is very ___.", exampleHe: "היא מאוד מפורסמת." },
        { en: "actually", he: "למעשה", phonetic: "/ˈæktʃuəli/", example: "___, I changed my mind.", exampleHe: "למעשה, שיניתי את דעתי." },
        { en: "necessary", he: "הכרחי", phonetic: "/ˈnɛsəsəri/", example: "It is ___ to study.", exampleHe: "זה הכרחי ללמוד." },
        { en: "receive", he: "לקבל", phonetic: "/rɪˈsiːv/", example: "I ___ a gift.", exampleHe: "אני מקבל מתנה." },
    ],
    advanced: [
        { en: "consequently", he: "כתוצאה מכך", phonetic: "/ˈkɒnsɪkwəntli/", example: "He didn't study, ___ he failed.", exampleHe: "הוא לא למד, כתוצאה מכך הוא נכשל." },
        { en: "sophisticated", he: "מתוחכם", phonetic: "/səˈfɪstɪkeɪtɪd/", example: "This is a ___ system.", exampleHe: "זו מערכת מתוחכמת." },
        { en: "approximately", he: "בערך", phonetic: "/əˈprɒksɪmətli/", example: "There are ___ 100 people.", exampleHe: "יש בערך 100 אנשים." },
        { en: "entrepreneur", he: "יזם", phonetic: "/ˌɒntrəprəˈnɜːr/", example: "She is a successful ___.", exampleHe: "היא יזמית מצליחה." },
        { en: "nevertheless", he: "בכל זאת", phonetic: "/ˌnɛvəðəˈlɛs/", example: "It was hard, ___ we succeeded.", exampleHe: "זה היה קשה, בכל זאת הצלחנו." },
        { en: "extraordinary", he: "יוצא דופן", phonetic: "/ɪkˈstrɔːrdɪnəri/", example: "What an ___ achievement!", exampleHe: "איזה הישג יוצא דופן!" },
        { en: "circumstance", he: "נסיבה", phonetic: "/ˈsɜːrkəmstəns/", example: "Under no ___ should you go.", exampleHe: "בשום נסיבה אל תלך." },
        { en: "acknowledge", he: "להכיר", phonetic: "/əkˈnɒlɪdʒ/", example: "We ___ your contribution.", exampleHe: "אנחנו מכירים בתרומתך." },
        { en: "comprehensive", he: "מקיף", phonetic: "/ˌkɒmprɪˈhɛnsɪv/", example: "This is a ___ guide.", exampleHe: "זה מדריך מקיף." },
        { en: "determination", he: "נחישות", phonetic: "/dɪˌtɜːrmɪˈneɪʃən/", example: "Her ___ is inspiring.", exampleHe: "הנחישות שלה מעוררת השראה." },
        { en: "exaggerate", he: "להגזים", phonetic: "/ɪɡˈzædʒəreɪt/", example: "Don't ___ the problem.", exampleHe: "אל תגזים עם הבעיה." },
        { en: "phenomenon", he: "תופעה", phonetic: "/fɪˈnɒmɪnɒn/", example: "It is a natural ___.", exampleHe: "זו תופעה טבעית." },
        { en: "perspective", he: "נקודת מבט", phonetic: "/pərˈspɛktɪv/", example: "Try to see it from my ___.", exampleHe: "נסה לראות את זה מנקודת המבט שלי." },
        { en: "enthusiastic", he: "נלהב", phonetic: "/ɪnˌθjuːziˈæstɪk/", example: "She is very ___ about it.", exampleHe: "היא מאוד נלהבת מזה." },
        { en: "vulnerability", he: "פגיעות", phonetic: "/ˌvʌlnərəˈbɪlɪti/", example: "We need to address this ___.", exampleHe: "אנחנו צריכים לטפל בפגיעות הזו." },
        { en: "accommodate", he: "להתאים", phonetic: "/əˈkɒmədeɪt/", example: "We can ___ your request.", exampleHe: "אנחנו יכולים להתאים לבקשתך." },
        { en: "bureaucracy", he: "בירוקרטיה", phonetic: "/bjʊˈrɒkrəsi/", example: "The ___ slows everything down.", exampleHe: "הבירוקרטיה מאטה הכל." },
        { en: "consciousness", he: "תודעה", phonetic: "/ˈkɒnʃəsnəs/", example: "He lost ___ for a moment.", exampleHe: "הוא איבד את ההכרה לרגע." },
        { en: "deteriorate", he: "להידרדר", phonetic: "/dɪˈtɪəriəreɪt/", example: "The situation began to ___.", exampleHe: "המצב התחיל להידרדר." },
        { en: "ambiguous", he: "דו-משמעי", phonetic: "/æmˈbɪɡjuəs/", example: "The answer was ___.", exampleHe: "התשובה הייתה דו-משמעית." },
        { en: "contemplate", he: "להתבונן", phonetic: "/ˈkɒntəmpleɪt/", example: "I ___ the meaning of life.", exampleHe: "אני מתבונן במשמעות החיים." },
        { en: "infrastructure", he: "תשתית", phonetic: "/ˈɪnfrəstrʌktʃər/", example: "The ___ needs improvement.", exampleHe: "התשתית צריכה שיפור." },
        { en: "overwhelming", he: "מכריע", phonetic: "/ˌoʊvərˈwɛlmɪŋ/", example: "The support was ___.", exampleHe: "התמיכה הייתה מכריעה." },
        { en: "procurement", he: "רכש", phonetic: "/prəˈkjʊərmənt/", example: "The ___ department handles orders.", exampleHe: "מחלקת הרכש מטפלת בהזמנות." },
        { en: "simultaneous", he: "סימולטני", phonetic: "/ˌsɪməlˈteɪniəs/", example: "The events were ___.", exampleHe: "האירועים היו סימולטניים." },
        { en: "unanimous", he: "פה אחד", phonetic: "/juˈnænɪməs/", example: "The decision was ___.", exampleHe: "ההחלטה הייתה פה אחד." },
        { en: "unprecedented", he: "חסר תקדים", phonetic: "/ʌnˈprɛsɪdɛntɪd/", example: "This is an ___ event.", exampleHe: "זה אירוע חסר תקדים." },
        { en: "miscellaneous", he: "שונות", phonetic: "/ˌmɪsəˈleɪniəs/", example: "I have ___ tasks to do.", exampleHe: "יש לי משימות שונות לעשות." },
        { en: "perseverance", he: "התמדה", phonetic: "/ˌpɜːrsɪˈvɪərəns/", example: "___ is the key to success.", exampleHe: "התמדה היא המפתח להצלחה." },
        { en: "quintessential", he: "מהותי", phonetic: "/ˌkwɪntɪˈsɛnʃəl/", example: "This is the ___ example.", exampleHe: "זו הדוגמה המהותית." },
    ]
};
